"""
End-to-End Pipeline: UI Test Agent → Bug-Fix Agent → PR

Demonstrates the full automated QA pipeline:
1. UI Test Agent finds bugs in the demo frontend
2. Bug-Fix Agent generates a patch
3. Script creates a PR with the fix

Usage:
    python e2e_pipeline.py
"""

import boto3
import json
import uuid
import subprocess

REGION = "us-east-1"
UI_TEST_HARNESS = "arn:aws:bedrock-agentcore:us-east-1:677207132843:harness/UITestAgentHarness-zIefA987hf"
BUG_FIX_HARNESS = "arn:aws:bedrock-agentcore:us-east-1:677207132843:harness/BugFixAgentHarness-F05tJBICHZ"
TARGET_URL = "https://timwukp.github.io/Harness-agentic-AI-agent-best-practices-and-use-case/demo/index.html"


def run_ui_test():
    """Step 1: Run UI Test Agent to find bugs."""
    print("=" * 60)
    print("STEP 1: Running UI Test Agent...")
    print("=" * 60)

    client = boto3.client("bedrock-agentcore", region_name=REGION)
    session_id = str(uuid.uuid4())

    response = client.invoke_harness(
        harnessArn=UI_TEST_HARNESS,
        runtimeSessionId=session_id,
        messages=[{"role": "user", "content": [{"text": f"""
Test {TARGET_URL}

Test cases:
1. Type wronguser/wrong, click Login - check if error says 'invalid credentials'
2. Check error message CSS color - should be red
3. Submit with empty password only (username filled) - check validation

Report PASS/FAIL with the exact issue for each FAIL.
"""}]}],
    )

    result_text = ""
    for event in response["stream"]:
        if "contentBlockDelta" in event:
            delta = event["contentBlockDelta"].get("delta", {})
            if "text" in delta:
                result_text += delta["text"]
                print(delta["text"], end="", flush=True)

    print("\n")
    return result_text


def run_bug_fix(test_results: str):
    """Step 2: Run Bug-Fix Agent to generate a patch."""
    print("=" * 60)
    print("STEP 2: Running Bug-Fix Agent...")
    print("=" * 60)

    client = boto3.client("bedrock-agentcore", region_name=REGION)
    session_id = str(uuid.uuid4())

    # Read the current source code
    with open("../demo-frontend/index.html") as f:
        source_code = f.read()

    response = client.invoke_harness(
        harnessArn=BUG_FIX_HARNESS,
        runtimeSessionId=session_id,
        messages=[{"role": "user", "content": [{"text": f"""
Here are test failures from our UI Test Agent:

{test_results}

Here is the source code of the page (index.html):

```html
{source_code}
```

Generate a unified diff patch that fixes ALL the reported bugs.
Output ONLY the diff, nothing else.
"""}]}],
    )

    patch_text = ""
    for event in response["stream"]:
        if "contentBlockDelta" in event:
            delta = event["contentBlockDelta"].get("delta", {})
            if "text" in delta:
                patch_text += delta["text"]
                print(delta["text"], end="", flush=True)

    print("\n")
    return patch_text


def create_pr(patch_description: str):
    """Step 3: Create a PR with the fix."""
    print("=" * 60)
    print("STEP 3: Creating PR...")
    print("=" * 60)

    # Create branch and PR using git/gh CLI
    branch = f"fix/auto-bugfix-{uuid.uuid4().hex[:8]}"
    subprocess.run(["git", "checkout", "-b", branch], check=True)
    subprocess.run(["git", "add", "-A"], check=True)
    subprocess.run(["git", "commit", "--no-verify", "-m", "fix: auto-generated bug fixes from UI Test Agent"], check=True)
    subprocess.run(["git", "push", "-u", "origin", branch, "--no-verify"], check=True)

    result = subprocess.run(
        ["gh", "pr", "create", "--title", "fix: auto-generated bug fixes",
         "--body", f"## Auto-Fix by Bug-Fix Agent\n\n{patch_description}\n\n---\n*Generated by Bug-Fix Agent based on UI Test Agent findings.*",
         "--base", "main", "--head", branch],
        capture_output=True, text=True
    )
    print(f"✅ PR created: {result.stdout.strip()}")


if __name__ == "__main__":
    # Step 1
    test_results = run_ui_test()

    # Step 2
    if "FAIL" in test_results:
        patch = run_bug_fix(test_results)
        print(f"\n📋 Bug-Fix Agent generated patch ({len(patch)} chars)")

        # Step 3 would apply the patch and create PR
        # For now, just show the result
        print("\n" + "=" * 60)
        print("PIPELINE COMPLETE")
        print("=" * 60)
        print(f"✅ UI Test Agent found bugs")
        print(f"✅ Bug-Fix Agent generated fix")
        print(f"📐 PR creation ready (apply patch manually or automate)")
    else:
        print("✅ All tests passed! No bugs to fix.")
